// <auto-generated />
using System;
using Library_Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Api.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_Api.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Jonathan Swift"
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Robert Louis Steverson"
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "J. K. Rowling"
                        },
                        new
                        {
                            AuthorId = 4,
                            Name = "Jennifer Niven"
                        },
                        new
                        {
                            AuthorId = 5,
                            Name = "Stephen King"
                        },
                        new
                        {
                            AuthorId = 6,
                            Name = "Coolen Hover"
                        },
                        new
                        {
                            AuthorId = 7,
                            Name = "Charlie Donlea"
                        });
                });

            modelBuilder.Entity("Library_Api.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PublishingCompany")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlWebImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearLauch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Edition = 1,
                            Name = "Gulliver's Travels",
                            Price = 59m,
                            PublishingCompany = "Pearson English",
                            UrlWebImg = "https://m.media-amazon.com/images/I/51W6w1PrkbL._SX384_BO1,204,203,200_.jpg",
                            YearLauch = "1726"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            Edition = 3,
                            Name = "Dr Jekyll & Mr Hyde",
                            Price = 53.91m,
                            PublishingCompany = "Bantam Books",
                            UrlWebImg = "https://m.media-amazon.com/images/I/71F0gmdm8pL.jpg",
                            YearLauch = "1982"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3,
                            Edition = 1,
                            Name = "Harry Potter and the Philosopher's Stone",
                            Price = 30.99m,
                            PublishingCompany = "Rocco",
                            UrlWebImg = "https://m.media-amazon.com/images/I/61jgm6ooXzL.jpg",
                            YearLauch = "2000"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4,
                            Edition = 5,
                            Name = "Por Lugares Incriveis",
                            Price = 60m,
                            PublishingCompany = "Seguinte",
                            UrlWebImg = "https://m.media-amazon.com/images/I/510HCDDGb3L._SY344_BO1,204,203,200_QL70_ML2_.jpg",
                            YearLauch = "2015"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5,
                            Edition = 1,
                            Name = "it a coisa",
                            Price = 45m,
                            PublishingCompany = "Suma",
                            UrlWebImg = "https://m.media-amazon.com/images/I/51z0s3GcvwL._SY344_BO1,204,203,200_QL70_ML2_.jpg",
                            YearLauch = "2014"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 6,
                            Edition = 1,
                            Name = "É assim que acaba",
                            Price = 30m,
                            PublishingCompany = "Galera",
                            UrlWebImg = "https://m.media-amazon.com/images/I/51i7kH+rh9L._SY344_BO1,204,203,200_.jpg",
                            YearLauch = "2018"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 7,
                            Edition = 1,
                            Name = "A garota do Lago",
                            Price = 80m,
                            PublishingCompany = "Scholastic Press",
                            UrlWebImg = "https://m.media-amazon.com/images/I/516VOgxwg2L._SY344_BO1,204,203,200_QL70_ML2_.jpg",
                            YearLauch = "2022"
                        });
                });

            modelBuilder.Entity("Library_Api.Entities.Book", b =>
                {
                    b.HasOne("Library_Api.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
