// <auto-generated />
using System;
using Livraria_Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Livraria_Api.Migrations
{
    [DbContext(typeof(LivrariaContext))]
    [Migration("20230301143039_PopularTabelas")]
    partial class PopularTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Livraria_Api.Entities.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            Nome = "JONATHAN SWIFT"
                        },
                        new
                        {
                            AutorId = 2,
                            Nome = "ROBERT LOUIS STEVERSON"
                        },
                        new
                        {
                            AutorId = 3,
                            Nome = "J. K. Rowling"
                        });
                });

            modelBuilder.Entity("Livraria_Api.Entities.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivroId"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LivroId");

                    b.HasIndex("AutorId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            LivroId = 1,
                            AutorId = 1,
                            DataLancamento = new DateTime(1726, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Edicao = 1,
                            Editora = "OXFORD BOOKWORMS",
                            Nome = "Gulliver's Travels"
                        },
                        new
                        {
                            LivroId = 2,
                            AutorId = 2,
                            DataLancamento = new DateTime(1986, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Edicao = 3,
                            Editora = "RIchmond READERS",
                            Nome = "Dr Jekyll & Mr Hyde"
                        },
                        new
                        {
                            LivroId = 3,
                            AutorId = 3,
                            DataLancamento = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Edicao = 2,
                            Editora = "Editora Rocco",
                            Nome = "Harry Potter and the Philosopher's Stone"
                        });
                });

            modelBuilder.Entity("Livraria_Api.Entities.Livro", b =>
                {
                    b.HasOne("Livraria_Api.Entities.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId");

                    b.Navigation("Autor");
                });
#pragma warning restore 612, 618
        }
    }
}
